MVCForum.Website/Areas/Admin/ViewModels/AdminCategoryViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using System.Web.Mvc.Routing.Constraints;
using DataAnnotationsExtensions;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;

namespace MVCForum.Website.Areas.Admin.ViewModels
{
    public class ListCategoriesViewModel
    {
        public IEnumerable<Category> Categories { get; set; }
    }

    public class CreateCategoryViewModel
    {
        [HiddenInput]
        public Guid Id { get; set; }

        [DisplayName("Category Name")]
        [Required]
        [StringLength(600)]
        public string Name { get; set; }

        [DisplayName("Category Description")]
        [DataType(DataType.MultilineText)]
        [UIHint(AppConstants.EditorType), AllowHtml]
        public string Description { get; set; }

        [DisplayName("Lock The Category")]
        public bool IsLocked { get; set; }

        [DisplayName("Moderate all topics in this Category")]
        public bool ModerateTopics { get; set; }

        [DisplayName("Moderate all posts in this Category")]
        public bool ModeratePosts { get; set; }

        [DisplayName("Sort Order")]
        [Numeric]
        public int SortOrder { get; set; }

        [DisplayName("Parent Category")]
        public Guid? ParentCategory { get; set; }

        public List<Category> AllCategories { get; set; }

        [DisplayName("Page Title")]
        [MaxLength(80)]
        public string PageTitle { get; set; }

        [DisplayName("Meta Desc")]
        [MaxLength(200)]
        public string MetaDesc { get; set; }
    }

    public class EditCategoryViewModel
    {
        [DisplayName("Category Name")]
        [Required]
        [StringLength(200)]
        public string Name { get; set; }

        [DisplayName("Category Description")]
        [DataType(DataType.MultilineText)]
        [UIHint(AppConstants.EditorType), AllowHtml]
        public string Description { get; set; }

        [DisplayName("Lock The Category")]
        public bool IsLocked { get; set; }

        [DisplayName("Moderate all topics in this Category")]
        public bool ModerateTopics { get; set; }

        [DisplayName("Moderate all posts in this Category")]
        public bool ModeratePosts { get; set; }

        [DisplayName("Sort Order")]
        [Numeric]
        public int SortOrder { get; set; }

        [HiddenInput]
        public Guid Id { get; set; }

        [DisplayName("Parent Category")]
        public Guid? ParentCategory { get; set; }

        public List<Category> AllCategories { get; set; }

        [DisplayName("Page Title")]
        [MaxLength(80)]
        public string PageTitle { get; set; }

        [DisplayName("Meta Desc")]
        [MaxLength(200)]
        public string MetaDesc { get; set; }
    }

    public class DeleteCategoryViewModel
    {
        [HiddenInput]
        public Guid Id { get; set; }

        public Category Category { get; set; }

        public List<Category> SubCategories { get; set; }
    }
}

MVCForum.Website/Areas/Admin/Controllers/AdminCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Website.Areas.Admin.ViewModels;

namespace MVCForum.Website.Areas.Admin.Controllers
{
    [Authorize(Roles = AppConstants.AdminRoleName)]
    public partial class AdminCategoryController : BaseAdminController
    {
        private readonly ICategoryService _categoryService;

        public AdminCategoryController(ILoggingService loggingService,
                                        IUnitOfWorkManager unitOfWorkManager,
                                       IMembershipService membershipService,
                                       ILocalizationService localizationService,
                                       ICategoryService categoryService,
                                       ISettingsService settingsService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, settingsService)
        {
            _categoryService = categoryService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public PartialViewResult ListAllCategories(Guid id)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var viewModel = new ListCategoriesViewModel
                                    {
                                        Categories = _categoryService.GetAllSubCategories(id)
                                    };
                return PartialView(viewModel);
            }
        }

        [ChildActionOnly]
        public PartialViewResult GetMainCategories()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var viewModel = new ListCategoriesViewModel
                                    {
                                        Categories = _categoryService.GetAll().OrderBy(x => x.SortOrder)
                                    };
                return PartialView(viewModel);
            }
        }

        [ChildActionOnly]
        public PartialViewResult CreateCategory()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var categoryViewModel = new CreateCategoryViewModel { AllCategories = _categoryService.GetAll().ToList() };
                return PartialView(categoryViewModel);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCategory(CreateCategoryViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    try
                    {
                        var category = new Category
                                           {
                                               Name = categoryViewModel.Name,
                                               Description = categoryViewModel.Description,
                                               IsLocked = categoryViewModel.IsLocked,
                                               ModeratePosts = categoryViewModel.ModeratePosts,
                                               ModerateTopics = categoryViewModel.ModerateTopics,
                                               SortOrder = categoryViewModel.SortOrder,
                                               PageTitle = categoryViewModel.PageTitle,
                                               MetaDescription = categoryViewModel.MetaDesc
                                           };

                        

                        if (categoryViewModel.ParentCategory != null)
                        {
                            var parentCategory = _categoryService.Get(categoryViewModel.ParentCategory.Value);
                            category.ParentCategory = parentCategory;
                            SortPath(category, parentCategory);
                        }

                        _categoryService.Add(category);

                        // We use temp data because we are doing a redirect
                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                                                                        {
                                                                            Message = "Category Created",
                                                                            MessageType =
                                                                                GenericMessages.success
                                                                        };
                        unitOfWork.Commit();
                    }
                    catch (Exception)
                    {
                        unitOfWork.Rollback();
                    }
                }
            }
            else
            {
                ModelState.AddModelError("", "There was an error creating the category");
            }

            return RedirectToAction("Index");
        }


        private EditCategoryViewModel CreateEditCategoryViewModel(Category category)
        {
            var categoryViewModel = new EditCategoryViewModel
            {
                Name = category.Name,
                Description = category.Description,
                IsLocked = category.IsLocked,
                ModeratePosts = category.ModeratePosts == true,
                ModerateTopics = category.ModerateTopics == true,
                SortOrder = category.SortOrder,
                Id = category.Id,
                PageTitle = category.PageTitle,
                MetaDesc = category.MetaDescription,
                ParentCategory = category.ParentCategory == null ? Guid.Empty : category.ParentCategory.Id,
                AllCategories = _categoryService.GetAll()
                    .Where(x => x.Id != category.Id)
                    .ToList()
            };
            return categoryViewModel;
        }

        public ActionResult EditCategory(Guid id)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var category = _categoryService.Get(id);
                var categoryViewModel = CreateEditCategoryViewModel(category);

                return View(categoryViewModel);
            }
        }

        [HttpPost]
        public ActionResult EditCategory(EditCategoryViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    try
                    {
                        var category = _categoryService.Get(categoryViewModel.Id);

                        category.Description = categoryViewModel.Description;
                        category.IsLocked = categoryViewModel.IsLocked;
                        category.ModeratePosts = categoryViewModel.ModeratePosts;
                        category.ModerateTopics = categoryViewModel.ModerateTopics;
                        category.Name = categoryViewModel.Name;
                        category.SortOrder = categoryViewModel.SortOrder;
                        category.PageTitle = categoryViewModel.PageTitle;
                        category.MetaDescription = categoryViewModel.MetaDesc;

                        if (categoryViewModel.ParentCategory != null)
                        {
                            // Set the parent category
                            var parentCategory = _categoryService.Get(categoryViewModel.ParentCategory.Value);
                            category.ParentCategory = parentCategory;

                            // Append the path from the parent category
                            SortPath(category, parentCategory);
                        }
                        else
                        {
                            // Must access property (trigger lazy-loading) before we can set it to null (Entity Framework bug!!!)
                            var triggerEfLoad = category.ParentCategory;
                            category.ParentCategory = null;

                            // Also clear the path
                            category.Path = null;
                        }

                        _categoryService.UpdateSlugFromName(category);

                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                                                                        {
                                                                            Message = "Category Updated",
                                                                            MessageType = GenericMessages.success
                                                                        };

                        categoryViewModel = CreateEditCategoryViewModel(category);

                        unitOfWork.Commit();
                    }
                    catch (Exception ex)
                    {
                        LoggingService.Error(ex);
                        unitOfWork.Rollback();

                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = "Category Update Failed",
                            MessageType = GenericMessages.error
                        };
                    }
                }
            }

            return View(categoryViewModel);
        }

        private void SortPath(Category category, Category parentCategory)
        {
            // Append the path from the parent category
            var path = string.Empty;
            if (!string.IsNullOrEmpty(parentCategory.Path))
            {

MVCForum.Website/Areas/Admin/Views/AdminCategory/CreateCategory.cshtml
@model MVCForum.Website.Areas.Admin.ViewModels.CreateCategoryViewModel


@section AdminHeader
{
    @(
 Bundle.JavaScript()
            .Add("~/Scripts/jquery.validate.min.js")
            .Add("~/Scripts/jquery.validate.unobtrusive.min.js")
            .MvcRender("~/scripts/cache/validate-combined_#.js")
    )
}


@using (Html.BeginForm("CreateCategory", "AdminCategory", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(false)
    @Html.AntiForgeryToken()
    <fieldset>
        <legend>Create New Category</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-field n3ocheckboxfield">
            @Html.EditorFor(model => model.IsLocked)
            @Html.LabelFor(model => model.IsLocked)
            @Html.ValidationMessageFor(model => model.IsLocked)
        </div>

        <div class="editor-field n3ocheckboxfield">
            @Html.EditorFor(model => model.ModerateTopics)
            @Html.LabelFor(model => model.ModerateTopics)
            @Html.ValidationMessageFor(model => model.ModerateTopics)
        </div>

        <div class="editor-field n3ocheckboxfield">
            @Html.EditorFor(model => model.ModeratePosts)
            @Html.LabelFor(model => model.ModeratePosts)
            @Html.ValidationMessageFor(model => model.ModeratePosts)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SortOrder)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SortOrder)
            @Html.ValidationMessageFor(model => model.SortOrder)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ParentCategory)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.ParentCategory, new SelectList(Model.AllCategories, "id", "Name"), string.Empty)
            @Html.ValidationMessageFor(model => model.ParentCategory)
        </div>

        <div class="well well-small">
            <div class="editor-label">
                @Html.LabelFor(model => model.PageTitle)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.PageTitle)
                @Html.ValidationMessageFor(model => model.PageTitle)
            </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.MetaDesc)
            </div>
            <div class="editor-field">
                @Html.TextAreaFor(model => model.MetaDesc)
                @Html.ValidationMessageFor(model => model.MetaDesc)
            </div>
        </div>

        <div class="submit-holder">
            <input type="submit" class="btn btn-large btn-success" value="Create" />
        </div>
    </fieldset>
}

MVCForum.Website/Areas/Admin/Views/AdminCategory/DeleteCategoryConfirmation.cshtml
@model MVCForum.Website.Areas.Admin.ViewModels.DeleteCategoryViewModel

@{
    ViewBag.Title = "Delete Category";

    if (Model.SubCategories.Any())
    {
        <h2>Unable To Delete</h2>
        <p>This category has sub categories, please re-assign them to new parent categories first</p>
        
        <h4>Sub Categories</h4>
        <ul>
            @foreach (var subCat in Model.SubCategories)
            {
                <li><strong>@subCat.Name</strong></li>
            }
        </ul>
        
        <a href="@Url.Action("Index")" class="btn btn-large btn-success">Back</a>
    }
    else if (Model.Category.Topics.Any())
    {
        <h2>Unable To Delete</h2>
        <p>This category has discussions associated with it, please either delete or move the topics to a different category</p>
        
        <h4>Topics</h4>
        <ul>
            @foreach (var topic in Model.Category.Topics)
            {
                <li><a href="@topic.NiceUrl">@topic.Name</a></li>
            }
        </ul>
        
        <a href="@Url.Action("Index")" class="btn btn-large btn-success">Back</a>
    }
    else
    {
        using (Html.BeginForm("DeleteCategory", "AdminCategory", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <h2>Delete Category?</h2>        
            <p>Are you sure you want to delete this Category</p>
            @Html.HiddenFor(x => x.Id)
            <div class="submit-holder">
                <input type="submit" class="btn btn-large btn-success" value="Yes" /> 
            </div>
        }
    }
}     

MVCForum.Website/Areas/Admin/Views/AdminCategory/EditCategory.cshtml
@model MVCForum.Website.Areas.Admin.ViewModels.EditCategoryViewModel

@{
    ViewBag.Title = "Edit Category";    
}

@section AdminHeader
{
        @(
        Bundle.JavaScript()
            .Add("~/Scripts/jquery.validate.min.js")
            .Add("~/Scripts/jquery.validate.unobtrusive.min.js")            
            .MvcRender("~/scripts/cache/validate-combined_#.js")
    )  
}

@using (Html.BeginForm("EditCategory", "AdminCategory", FormMethod.Post, new { @class = "form-horizontal" }))
{
        @Html.ValidationSummary(false)
    <fieldset>
        <legend>Edit Category</legend>
        
        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-field n3ocheckboxfield">
            @Html.EditorFor(model => model.IsLocked)
            @Html.LabelFor(model => model.IsLocked)
            @Html.ValidationMessageFor(model => model.IsLocked)
        </div>
        
        <div class="editor-field n3ocheckboxfield">
            @Html.EditorFor(model => model.ModerateTopics)
            @Html.LabelFor(model => model.ModerateTopics)
            @Html.ValidationMessageFor(model => model.ModerateTopics)
        </div>
        
        <div class="editor-field n3ocheckboxfield">
            @Html.EditorFor(model => model.ModeratePosts)
            @Html.LabelFor(model => model.ModeratePosts)
            @Html.ValidationMessageFor(model => model.ModeratePosts)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SortOrder)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SortOrder)
            @Html.ValidationMessageFor(model => model.SortOrder)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ParentCategory)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.ParentCategory, new SelectList(Model.AllCategories, "id", "Name"), string.Empty)
            @Html.ValidationMessageFor(model => model.ParentCategory)
        </div>
        
        <div class="well well-small">
            <div class="editor-label">
                @Html.LabelFor(model => model.PageTitle)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.PageTitle)
                @Html.ValidationMessageFor(model => model.PageTitle)
            </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.MetaDesc)
            </div>
            <div class="editor-field">
                @Html.TextAreaFor(model => model.MetaDesc)
                @Html.ValidationMessageFor(model => model.MetaDesc)
            </div>
        </div>

        <div class="submit-holder">
            <input type="submit" class="btn btn-large btn-success" value="Update" />
        </div>
    </fieldset>
}

MVCForum.Website/Areas/Admin/Views/AdminCategory/GetMainCategories.cshtml
@using System.Net.Mime
@model MVCForum.Website.Areas.Admin.ViewModels.ListCategoriesViewModel
@{
    var mainCategories = Model.Categories.Where(x => x.ParentCategory == null).ToList();
}


@if (mainCategories.Any())
{
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Main Categories</th>
                <th>Sub Categories</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cat in mainCategories)
            {
                var category = cat;
                var allSubCategorys = Model.Categories.Where(x => x.Path != null && x.Path.ToLower().Contains(category.Id.ToString().ToLower())).ToList();
                <tr>
                    <td class="editcategory mainadmincategory">
                        <a href="@Url.Action("EditCategory", new { id = cat.Id })">@Html.Raw(cat.Name)</a>
                    </td>
                    <td>
                        @if (allSubCategorys.Any())
                        {
                            <ul class="subcatslist">
                                @foreach (var subCat in allSubCategorys)
                                {
                                    <li><a href="@Url.Action("EditCategory", new { id = subCat.Id })">@Html.Raw(subCat.Name)</a></li>
                                }
                            </ul>
                        }
                    </td>
                    <td>
                        <a href="@Url.Action("DeleteCategoryConfirmation", new { id = cat.Id })" title="Delete @Html.Raw(cat.Name)" class="btn btn-small"><i class="icon-remove"></i></a>
                    </td>
                </tr>

            }
        </tbody>
    </table>
}

<p><strong>What is this?</strong></p>
<p>If you upgraded to v1.5, then you will need to sync all the category paths for the new breadcrumb feature to work.</p>
<p><a href="@Url.Action("SyncCategoryPaths", "AdminCategory")" class="btn">Sync All Category Paths</a></p>

MVCForum.Website/Areas/Admin/Views/AdminCategory/Index.cshtml
@{
    ViewBag.Title = "Manage Categories";
}

@section AdminHeader
{
    <script type="text/javascript">
        // Can also use beforeClose ?
        $('.catfancybox').fancybox({
            type: 'iframe',
            padding: 15,
            afterClose: function () {
                parent.location.reload(true);
            }
        });
    </script>
}


<div class="tabbable">
    <ul class="nav nav-tabs" id="myTab">
        <li class="active"><a data-toggle="tab" href="#maincats">Categories</a></li>
        <li><a data-toggle="tab" href="#createnew">Create New</a></li>
    </ul>


    <div class="tab-content">
        <div class="tab-pane active" id="maincats">
            <div class="row-fluid">
                <div class="span12">
                    @Html.Action("GetMainCategories")
                </div>
            </div>
        </div>
        <div class="tab-pane" id="createnew">
            <div class="row-fluid">
                <div class="span12">
                    @Html.Action("CreateCategory")
                </div>
            </div>
        </div>
    </div>
</div>

MVCForum.Website/Areas/Admin/Views/AdminCategory/ListAllCategories.cshtml
@model MVCForum.Website.Areas.Admin.ViewModels.ListCategoriesViewModel

@{
    if(Model.Categories.Any())
    {
        <ul class="subcategorylist">
        @foreach (var cat in Model.Categories)
        {
            <li class="subcategoryitem"><a href="@Url.Action("EditCategory", new {id = cat.Id})">@Html.Raw(cat.Name)</a>
            <a href="@Url.Action("DeleteCategoryConfirmation", new {id = cat.Id})"><img src="/Content/admin/Images/icons/cross.png" alt="Delete" title="Delete @Html.Raw(cat.Name)" /></a></li>
            @Html.Action("ListAllCategories", new { id = cat.Id })
        }
        </ul>
    }
}

MVCForum.Website/Areas/Admin/Views/AdminCategory/PopupConfirm.cshtml
@{
    Layout = "~/Areas/Admin/Views/shared/_AdminBlankLayout.cshtml";
}

<script type="text/javascript">
    $(function () {
        parent.delay(800).$.fancybox.close();
    });
</script>