MVCForum.Website/Areas/Admin/ViewModels/BannedWordViewModels.cs
using System;
using System.ComponentModel.DataAnnotations;
using MVCForum.Domain.DomainModel;

namespace MVCForum.Website.Areas.Admin.ViewModels
{
    public class BannedWordListViewModel
    {
        public PagedList<BannedWord> Words { get; set; }

        public int? PageIndex { get; set; }
        public int? TotalCount { get; set; }
        public string Search { get; set; }
    }

    public class AddBannedWordViewModel
    {
        [Required]
        public string Word { get; set; }
    }

    public class AjaxEditWordViewModel
    {
        [Required]
        public Guid WordId { get; set; }

        [Required]
        public string NewName { get; set; }
    }
}

MVCForum.Website/Areas/Admin/Controllers/BannedWordController.cs
using System;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Website.Areas.Admin.ViewModels;

namespace MVCForum.Website.Areas.Admin.Controllers
{
    [Authorize(Roles = AppConstants.AdminRoleName)]
    public partial class BannedWordController : BaseAdminController
    {

        private readonly IBannedWordService _bannedWordService;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="unitOfWorkManager"> </param>
        /// <param name="membershipService"></param>
        /// <param name="localizationService"> </param>
        /// <param name="settingsService"> </param>
        /// <param name="loggingService"> </param>
        /// <param name="bannedWordService"></param>
        public BannedWordController(ILoggingService loggingService,
            IUnitOfWorkManager unitOfWorkManager,
            IMembershipService membershipService,
            ILocalizationService localizationService,
            ISettingsService settingsService, 
            IBannedWordService bannedWordService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, settingsService)
        {
            _bannedWordService = bannedWordService;
        }


        public ActionResult Index(int? p, string search)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var pageIndex = p ?? 1;
                var allEmails = string.IsNullOrEmpty(search) ? _bannedWordService.GetAllPaged(pageIndex, AppConstants.AdminListPageSize) :
                                    _bannedWordService.GetAllPaged(search, pageIndex, AppConstants.AdminListPageSize);

                var viewModel = new BannedWordListViewModel
                    {
                        Words = allEmails,
                        PageIndex = pageIndex,
                        TotalCount = allEmails.TotalCount,
                        Search = search
                    };
                
                return View(viewModel);
            }
            
        }

        [HttpPost]
        public ActionResult Add(AddBannedWordViewModel addBannedEmailViewModel)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                try
                {
                    if (!string.IsNullOrEmpty(addBannedEmailViewModel.Word))
                    {
                        var bannedWord = new BannedWord
                        {
                            Word = addBannedEmailViewModel.Word,
                            DateAdded = DateTime.Now
                        };

                        _bannedWordService.Add(bannedWord);

                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = "Word added",
                            MessageType = GenericMessages.success
                        };

                        unitOfWork.Commit();
                    }
                    else
                    {
                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = "Please add a word",
                            MessageType = GenericMessages.error
                        };
                    }

                }
                catch (Exception ex)
                {
                    unitOfWork.Rollback();
                    LoggingService.Error(ex);
                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = LocalizationService.GetResourceString("Errors.GenericMessage"),
                        MessageType = GenericMessages.error
                    }; 
                }
            }

            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid id, int? p, string search)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                try
                {
                    var word = _bannedWordService.Get(id);
                    if (word == null)
                    {
                        throw new ApplicationException("Cannot delete word - Word does not exist");
                    }

                    _bannedWordService.Delete(word);

                    ViewBag.Message = new GenericMessageViewModel
                    {
                        Message = "Word delete successfully",
                        MessageType = GenericMessages.success
                    };
                    unitOfWork.Commit();
                }
                catch (Exception ex)
                {
                    unitOfWork.Rollback();
                    LoggingService.Error(ex);
                    ViewBag.Message = new GenericMessageViewModel
                    {
                        Message = string.Format("Delete failed: {0}", ex.Message),
                        MessageType = GenericMessages.error
                    };
                }

                return RedirectToAction("Index", new { p, search });
            }
        }

        /// <summary>
        /// Edit a resource key
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public void AjaxUpdateWord(AjaxEditWordViewModel viewModel)
        {
            if (Request.IsAjaxRequest())
            {
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    try
                    {
                        var wordToUpdate = _bannedWordService.Get(viewModel.WordId);
                        wordToUpdate.Word = viewModel.NewName;
                        unitOfWork.Commit();
                    }
                    catch (Exception ex)
                    {
                        unitOfWork.Rollback();
                        LoggingService.Error(ex);
                    }
                }
            }
        }
    }
}

MVCForum.Website/Areas/Admin/Views/BannedWord/Index.cshtml
@using MVCForum.Domain.Constants
@model MVCForum.Website.Areas.Admin.ViewModels.BannedWordListViewModel
@{
    ViewBag.Title = "Banned Word";
}

<h2>@ViewBag.Title</h2>

<p>Banned words that are matched will be replaced with a charactor that you can define in a web.config app setting called BannedWordReplaceCharactor</p>
<p>By default its set to '?' (i.e. if you had <strong>feck</strong> in the list, it would become <strong>????</strong>). You can add a single word, or you can add wildcards at the end of your word.</p>
<p>For example, if you wanted to ban feck, fecking, feckers etc... You can add <strong>feck*</strong> which will match feck AND anything after.</p>

<div class="row-fluid">
    <div class="span5">
        @using (Html.BeginForm("Index", "BannedWord", FormMethod.Get, new { @class = "form-horizontal" }))
        {    
            <div class="search large-search input-append">
                @Html.TextBoxFor(x => Model.Search)
                <button class="btn">Search</button>
                @Html.Hidden("p", Model.PageIndex)
            </div>
        }
    </div>
    <div class="span5">
        @using (Html.BeginForm("Add", "BannedWord", FormMethod.Post, new { @class = "form-horizontal" }))
        {    
            <div class="search large-search input-append">
                @Html.TextBox("Word")
                <button class="btn">Add</button>
            </div>
        }
    </div>
</div>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Edit</th>
            <th>Word</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var word in Model.Words)
        {
            <tr>
                <td>
                    <span class="editbannedword">
                        <a href="#" class="btn btn-small">
                            <i class="icon-pencil"></i>
                        </a>
                    </span>
                    <span class="savebannedword" style="display: none;">
                        <a href="#" class="btn btn-small">
                            <i class="icon-ok"></i>
                        </a>
                    </span>
                </td>
                <td class="bannedwordvalue">                                       
                    <span class="bannedwordvaluedisplay">
                                  @Html.Raw(word.Word)
                    </span>
                    <span class="bannedwordvalueedit" style="display: none;">
                        <input data-wordid="@word.Id" data-oldvalue="@word.Word" type="text" id="@word.Id" value="@word.Word" class="bannedwordinput"/>
                    </span>
                </td>
                <td>
                    <a href="@Url.Action("Delete", new { word.Id, p = Model.PageIndex, search = Model.Search })" class="btn btn-small">
                        <i class="icon-remove"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

@if (Model.Words.TotalPages > 1)
{
    @Html.Pager(Convert.ToInt32(Model.PageIndex), AppConstants.AdminListPageSize, Convert.ToInt32(Model.TotalCount), new {search = Model.Search})
}

<div class="btn-group">
    @Html.ActionLink("Back", "Index", "Admin", new { Area = "Admin" }, new { @class = "btn btn-success" })
</div>