MVCForum.Website/Areas/Admin/ViewModels/AdminTagViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using MVCForum.Domain.DomainModel;

namespace MVCForum.Website.Areas.Admin.ViewModels
{
    public class ListTagsViewModel
    {
        public PagedList<TopicTag> Tags { get; set; }
        public int? PageIndex { get; set; }
        public int? TotalCount { get; set; }
        public string Search { get; set; }
    }

    public class AjaxEditTagViewModel
    {
        [Required]
        public string OldName { get; set; }

        [Required]
        public string NewName { get; set; }
    }
}

MVCForum.Website/Areas/Admin/Controllers/AdminTagController.cs
using System;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Website.Areas.Admin.ViewModels;
using MVCForum.Website.Controllers;

namespace MVCForum.Website.Areas.Admin.Controllers
{
    [Authorize(Roles = AppConstants.AdminRoleName)]
    public partial class AdminTagController : BaseController
    {
        private readonly ITopicTagService _topicTagService;

        public AdminTagController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, ILocalizationService localizationService, IRoleService roleService, ISettingsService settingsService, ITopicTagService topicTagService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, roleService, settingsService)
        {
            _topicTagService = topicTagService;
        }

        public ActionResult Index(int? p, string search)
        {
            var pageIndex = p ?? 1;

            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var allTags = string.IsNullOrEmpty(search) ? _topicTagService.GetPagedGroupedTags(pageIndex, AppConstants.AdminListPageSize) :
                            _topicTagService.SearchPagedGroupedTags(search, pageIndex, AppConstants.AdminListPageSize);

                var memberListModel = new ListTagsViewModel
                {
                    Tags = allTags,
                    PageIndex = pageIndex,
                    TotalCount = allTags.TotalCount,
                    Search = search
                };

                return View(memberListModel);
            }

        }

        public ActionResult Manage(int? p, string search)
        {
            return RedirectToAction("Index", new {p, search});
        }


        public ActionResult Delete(string tag)
        {


            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                _topicTagService.DeleteByName(tag);

                TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                {
                    Message = "Tags delete successfully",
                    MessageType = GenericMessages.success
                };

                try
                {
                    unitOfWork.Commit();
                }
                catch (Exception ex)
                {
                    unitOfWork.Rollback();
                    LoggingService.Error(ex);
                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = string.Format("Delete failed: {0}", ex.Message),
                        MessageType = GenericMessages.error
                    };
                }

            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public void UpdateTag(AjaxEditTagViewModel viewModel)
        {
            if (Request.IsAjaxRequest())
            {               
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    _topicTagService.UpdateTagNames(viewModel.NewName, viewModel.OldName);

                    try
                    {
                        unitOfWork.Commit();
                    }
                    catch (Exception ex)
                    {
                        unitOfWork.Rollback();
                        LoggingService.Error(ex);
                    }
                }
            }
        }

    }
}

MVCForum.Website/Areas/Admin/Views/AdminTag/Index.cshtml
@using MVCForum.Domain.Constants
@model MVCForum.Website.Areas.Admin.ViewModels.ListTagsViewModel

@{
    ViewBag.Title = "Tags";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Manage", "AdminTag", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="search large-search input-append">
        @Html.TextBoxFor(x => @Model.Search)
        <button class="btn">Search</button>
        @Html.HiddenFor(x => x.PageIndex)
    </div>
}



<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Edit</th>
            <th>Tag</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var tag in Model.Tags)
        {

            <tr>
                <td class="tagcell">
                    <span class="edittag">
                        <a href="#" class="btn btn-small">
                            <i class="icon-pencil"></i>
                        </a>
                    </span>
                    <span class="savetag" style="display:none;">
                        <a href="#" class="btn btn-small">
                            <i class="icon-ok"></i>
                        </a>
                    </span>
                </td>
                <td class="tagvalue">
                    <strong>
                        
                        <span class="tagvaluedisplay">
                            @tag.Tag
                        </span>
                        <span class="tagvalueedit" style="display:none;">
                            <input data-tagid="@tag.Id" data-oldvalue="@tag.Tag" type="text" id="@tag.Id" value="@tag.Tag" class="taginput"/>
                        </span>

                    </strong>
                </td>
                <td>

                    <a href="@Url.Action("Delete", new { tag = tag.Tag })" class="btn btn-small">
                        <i class="icon-remove"></i>
                    </a> 

                </td>
            </tr>
        }
    </tbody>
</table>

    @Html.Pager(Convert.ToInt32(Model.PageIndex), AppConstants.AdminListPageSize, Convert.ToInt32(Model.TotalCount), new { search = Model.Search })