MVCForum.Website/Areas/Admin/ViewModels/PermissionsViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using MVCForum.Domain.DomainModel;

namespace MVCForum.Website.Areas.Admin.ViewModels
{
    public class ChoosePermissionsViewModel
    {
        public List<MembershipRole> MembershipRoles { get; set; }
        public List<Permission> Permissions { get; set; } 
    }

    public class EditPermissionsViewModel
    {
        public MembershipRole MembershipRole { get; set; }
        public List<Permission> Permissions { get; set; }
        public List<Category> Categories { get; set; } 
    }

    public class AddTypeViewModel
    {
        [HiddenInput]
        public Guid Id { get; set; }

        [Required]
        [DisplayName("Permission Type Name")]
        [StringLength(200)]
        public string Name { get; set; }
    }

    public class EditTypeViewModel
    {
        [HiddenInput]
        public Guid Id { get; set; }

        [Required]
        [DisplayName("Permission Type Name")]
        [StringLength(200)]
        public string Name { get; set; }
    }

    public class AjaxEditPermissionViewModel
    {
        [Required]
        public bool HasPermission { get; set; }

        [Required]
        public Guid Permission { get; set; }
        
        [Required]
        public Guid MembershipRole { get; set; }

        [Required]
        public Guid Category { get; set; }
    }
}

MVCForum.Website/Areas/Admin/Controllers/PermissionsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Website.Areas.Admin.ViewModels;

namespace MVCForum.Website.Areas.Admin.Controllers
{
    [Authorize(Roles = AppConstants.AdminRoleName)]
    public partial class PermissionsController : BaseAdminController
    {
        private readonly IRoleService _roleService;
        private readonly IPermissionService _permissionService;
        private readonly ICategoryService _categoryService;
        private readonly ICategoryPermissionForRoleService _categoryPermissionForRoleService;

        public PermissionsController(ILoggingService loggingService, 
                                    IUnitOfWorkManager unitOfWorkManager, 
                                    IRoleService roleService,
                                    ILocalizationService localizationService,
                                    IPermissionService permissionService,
                                    ICategoryService categoryService,
                                    ICategoryPermissionForRoleService categoryPermissionForRoleService,
                                    IMembershipService membershipService,
                                    ISettingsService settingsService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, settingsService)
        {
            _roleService = roleService;
            _permissionService = permissionService;
            _categoryService = categoryService;
            _categoryPermissionForRoleService = categoryPermissionForRoleService;
        }

        /// <summary>
        /// List of roles to apply permissions to
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var permViewModel = new ChoosePermissionsViewModel
                                        {
                                            MembershipRoles = _roleService.AllRoles().ToList(),
                                            Permissions = _permissionService.GetAll().ToList()
                                        };
                return View(permViewModel);
            }
        }

        /// <summary>
        /// Add / Remove permissions for a role on each category
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult EditPermissions(Guid id)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var role = _roleService.GetRole(id);
                var permViewModel = new EditPermissionsViewModel
                                        {
                                            MembershipRole = role,
                                            Permissions = _permissionService.GetAll().ToList(),
                                            Categories = _categoryService.GetAll().ToList()
                                        };
                return View(permViewModel);
            }
        }

        /// <summary>
        /// Add a new permission type into the permission table
        /// </summary>
        /// <returns></returns>
        public ActionResult AddType()
        {
            return View(new AddTypeViewModel());
        }

        [HttpPost]
        public ActionResult AddType(AddTypeViewModel permissionViewModel)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                try
                {
                    var permission = new Permission
                                         {
                                             Name = permissionViewModel.Name,
                                         };
                        
                    _permissionService.Add(permission);
                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = "Permission Added",
                        MessageType = GenericMessages.success
                    };
                    unitOfWork.Commit();
                }
                catch(Exception ex)
                {
                    unitOfWork.Rollback();
                    LoggingService.Error(ex); 
                    throw;
                }
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public void UpdatePermission(AjaxEditPermissionViewModel ajaxEditPermissionViewModel)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                try
                {
                    if (Request.IsAjaxRequest())
                    {
                        var mappedItem = new CategoryPermissionForRole
                                             {
                                                 Category = _categoryService.Get(ajaxEditPermissionViewModel.Category),
                                                 MembershipRole =
                                                     _roleService.GetRole(ajaxEditPermissionViewModel.MembershipRole),
                                                 Permission =
                                                     _permissionService.Get(ajaxEditPermissionViewModel.Permission),
                                                 IsTicked = ajaxEditPermissionViewModel.HasPermission
                                             };
                        _categoryPermissionForRoleService.UpdateOrCreateNew(mappedItem);
                    }
                    unitOfWork.Commit();
                }
                catch (Exception ex)
                {
                    unitOfWork.Rollback();
                    LoggingService.Error(ex);
                    throw;
                }
            }
        }

        public ActionResult DeletePermission(Guid id)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                try
                {
                    var permission = _permissionService.Get(id);
                    _permissionService.Delete(permission);

                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                                                                    {
                                                                        Message = "Permission Deleted",
                                                                        MessageType = GenericMessages.success
                                                                    };
                    unitOfWork.Commit();
                }
                catch (Exception ex)
                {
                    unitOfWork.Rollback();
                    LoggingService.Error(ex);
                    throw;
                }
            }
            return RedirectToAction("Index");
        }

    }
}

MVCForum.Website/Areas/Admin/Views/Permissions/AddType.cshtml
@model MVCForum.Website.Areas.Admin.ViewModels.AddTypeViewModel

@{
    ViewBag.Title = "Add Permission Type";
}
@section AdminHeader
{
        @(
        Bundle.JavaScript()
            .Add("~/Scripts/jquery.validate.min.js")
            .Add("~/Scripts/jquery.validate.unobtrusive.min.js")            
            .MvcRender("~/scripts/cache/validate-combined_#.js")
    )  
}

@using (Html.BeginForm("AddType", "Permissions", FormMethod.Post, new { @class = "form-horizontal" })) 
{
    @Html.ValidationSummary(false)
    <fieldset>
        <legend>@ViewBag.Title</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="submit-holder">
            <input type="submit" class="btn btn-large btn-success" value="Create" />
        </div>
    </fieldset>
}

MVCForum.Website/Areas/Admin/Views/Permissions/EditPermissions.cshtml
@using MVCForum.Domain.Constants
@model MVCForum.Website.Areas.Admin.ViewModels.EditPermissionsViewModel

@{
    Layout = "~/Areas/Admin/Views/shared/_AdminFullWidthLayout.cshtml";
    ViewBag.Title = "Edit Permissions";
    var allPermission = Model.MembershipRole.GetFullPermissionTable();
}

<div class="container-fluid fluidheader">
    <div class="row-fluid">
        <div class="span1">
            <a href="@Url.Action("Index")" class="btn btn-large btn-success">Back</a>
        </div>
            <div class="span10">
                <h2>Edit @Model.MembershipRole.RoleName Permissions <img src="@Url.Content("~/Content/admin/Images/ajax-loader.gif")" alt="Please Wait" style="display: none;" class="editpermissionsspinner" /> <span class="label label-success ajaxsuccessshow" style="display: none;">Success</span></h2>
                <p>All permissions relate to all posts, topics i.e. If you enable edit and delete posts, any member in this role will be able edit and delete posts by any other member</p>
            </div>
    </div>
</div>

<div class="container-fluid">
    
    <div class="row-fluid">
        @Html.AntiForgeryToken()
        <table class="table table-bordered table-striped permissiontable">
    
            <thead>
                <tr>
                <th></th>
                @foreach(var permissionType in Model.Permissions)
                {
                    <th>@permissionType.Name</th>
                }
                </tr>
            </thead>
    
            <tbody>
                @foreach(var cat in Model.Categories)
                {
            
                    <tr>
                        <td>@cat.Name</td>
                        @foreach (var permission in Model.Permissions)
                        {
                            var isChecked = "";
                            var isDisabled = DisableCheckBox(permission.Name);                             
                            <td>
                        
                                @if (allPermission.ContainsKey(cat.Id) && allPermission[cat.Id].ContainsKey(permission))
                                {
                                    // bingo we have this permission
                                    isChecked = allPermission[cat.Id][permission] ? " checked" : "";                                    
                                }
                                <span class="permissioncheckbox">
                                    <input data-permisssion="@permission.Id" data-category="@cat.Id" data-role="@Model.MembershipRole.Id" 
                                    type="checkbox" id="@permission.Id-@cat.Id" @isChecked @isDisabled />
                                </span>
                            </td>
                        }
                    </tr>
                }
            </tbody>

        </table>

    </div>

</div>

@helper DisableCheckBox(string permissionName)
{
    if (Model.MembershipRole.RoleName == AppConstants.GuestRoleName &&
        permissionName != AppConstants.PermissionDenyAccess)
    {
        <text>disabled</text>
    }
    else
    {
        <text></text>
    }
}

MVCForum.Website/Areas/Admin/Views/Permissions/Index.cshtml
@using MVCForum.Domain.Constants
@model MVCForum.Website.Areas.Admin.ViewModels.ChoosePermissionsViewModel
@{
    ViewBag.Title = "Permissions";
}


<h2>Permissions</h2>
<p>This section allows you to update and edit permissions and assign new permissions to roles</p>

<div class="adminsection clearfix">

    <h3>Role Permissions</h3>
    <p>From this page you can set permissions per category for each role.</p>

    @foreach (var role in Model.MembershipRoles)
    {
        <ul class="rolepermissionlist">
            @if (role.RoleName != AppConstants.AdminRoleName)
            {
                <li><a href="@Url.Action("EditPermissions", new { role.Id })" class="btn">@role.RoleName</a></li>
            }
        </ul>
    }

</div>


<div class="adminsection clearfix">

    <div class="span5">
        <h3>Add Permissions</h3>
        <p>If you want to add your own custom permission, add it into the database using the button below.</p>
        <p>You will also need to add the name into the AppConstants file, as its used as the key.</p>

        <p><a href="@Url.Action("AddType")" class="btn btn-large btn-success">Add New Permission Type</a></p>
    </div>

    <div class="span4">

        <h3>Current Permission Types</h3>

        <p><strong><u style="color: maroon;">WARNING:</u></strong> Deleting permission types that are in use could break your forum, be very careful,</p>
        <ul>
            @foreach (var permission in Model.Permissions)
            {
                <li>@permission.Name (@Html.ActionLink("Delete", "DeletePermission", new { id = permission.Id }))</li>
            }
        </ul>
    </div>

</div>